import { addCardIds } from "../../src/utils"
import * as theAllCards from './cards-store' 
import { TCardPart } from "../typing/card"


export type TCard = TCardPart & {
  id: number
}

export const basicCards: TCard[] = addCardIds([
  theAllCards.c3,
  theAllCards.c3,
  theAllCards.c61,
  theAllCards.c70,
  theAllCards.c42,
  theAllCards.c103,
  theAllCards.c103,
  theAllCards.c60,
  theAllCards.c60,
  theAllCards.c41,
])


export const spiceMustFlowCards: TCard[] = addCardIds(Array.from({length: 10}).map(_ => theAllCards.c55))

export const fremenCards: TCard[] = addCardIds(Array.from({length: 9}).map(_ => theAllCards.c51))

export const spacingGuidCards: TCard[] = addCardIds(Array.from({length: 6}).map(_ => theAllCards.c76))


export const empireDeck = addCardIds([
  theAllCards.c1,
  theAllCards.c2,
  theAllCards.c2,
  theAllCards.c5,
  theAllCards.c6,  
  theAllCards.c7,  

  theAllCards.c9,
  theAllCards.c10,
  theAllCards.c10,
  theAllCards.c11,
  theAllCards.c11,
  theAllCards.c12,
  theAllCards.c12,
  theAllCards.c13,
  theAllCards.c14,
  theAllCards.c15,
  theAllCards.c16,
  theAllCards.c17,
  theAllCards.c18,
  theAllCards.c19,
  theAllCards.c19,
  theAllCards.c20,

  theAllCards.c21,
  theAllCards.c21,
  theAllCards.c22,
  theAllCards.c23,
  theAllCards.c24,
  theAllCards.c25,
  theAllCards.c25,
  theAllCards.c26,
  theAllCards.c27,
  theAllCards.c28,
  theAllCards.c29,
  theAllCards.c30,

  theAllCards.c31,
  theAllCards.c31,
  theAllCards.c32,
  theAllCards.c33,
  theAllCards.c33,
  theAllCards.c34,
  theAllCards.c34,
  theAllCards.c35,
  theAllCards.c36,
  theAllCards.c36,
  theAllCards.c37,
  theAllCards.c38,
  theAllCards.c39,
  theAllCards.c39,
  theAllCards.c40,
  theAllCards.c40,

  theAllCards.c43,
  theAllCards.c44,
  theAllCards.c44,
  theAllCards.c45,
  theAllCards.c46,
  theAllCards.c47,
  theAllCards.c48,
  theAllCards.c49,
  theAllCards.c50,
  theAllCards.c53,
  theAllCards.c53,
  theAllCards.c56,
  theAllCards.c57,
  theAllCards.c58,
  theAllCards.c58,
  theAllCards.c59,
  theAllCards.c59,
  theAllCards.c62,
  theAllCards.c62,
  theAllCards.c63,
  theAllCards.c64,
  theAllCards.c64,
  theAllCards.c65,
  theAllCards.c65,
  theAllCards.c66,
  theAllCards.c67,
  theAllCards.c68,
  theAllCards.c69,
  theAllCards.c71,
  theAllCards.c71,
  theAllCards.c72,
  theAllCards.c73,
  theAllCards.c74,
  theAllCards.c75,
  theAllCards.c77,
  theAllCards.c78,
  theAllCards.c78,
  theAllCards.c79,
  theAllCards.c80,
  theAllCards.c81,
  theAllCards.c82,
  theAllCards.c83,
  theAllCards.c84,
  theAllCards.c85,
  theAllCards.c85,
  theAllCards.c86,
  theAllCards.c87,
  theAllCards.c87,
  theAllCards.c88,
  theAllCards.c89,
  theAllCards.c90,
  theAllCards.c91,

  theAllCards.c93,
  theAllCards.c93,
  theAllCards.c94,
  theAllCards.c95,
  theAllCards.c96,
  theAllCards.c97,
  theAllCards.c98,
  theAllCards.c98,
  theAllCards.c99,
  theAllCards.c100,
  theAllCards.c101,
  theAllCards.c101,
  theAllCards.c102,
  theAllCards.c102,
  theAllCards.c104,
  theAllCards.c104,
])

export const allCards = [...basicCards, ...spacingGuidCards, ... fremenCards, ...spacingGuidCards, ...empireDeck]