

export enum EConstraint {
  'paySpice' = 'paySpice',
  'union2' = 'union2',
  'fremen2' = 'fremen2',
  'payWater' = 'payWater',
  'trashCard' = 'trashCard',
  'payMoney' = 'payMoney',
  'loseInf' = 'loseInf',
}

export enum EEffect {
  'trashCard' = 'trashCard',
  'getTroops' = 'getTroops',
  'getMoney' = 'getMoney',
  'getWater' = 'getWater',
  'getSpice' = 'getSpice',
  'cardBuy' = 'cardBuy',
  'TLLBuy' = 'TLLBuy',
  'dao' = 'dao', 
  'trashCardSelf' = 'trashCardSelf',
  'roleSkill' = "roleSkill",
  'research' = 'research',
  'paoC' = 'paoC',
  'collectSpice1' = 'collectSpice1',
  'collectSpice2' = 'collectSpice2',
  'collectSpice3' = 'collectSpice3',
  'drawCard' = 'drawCard',
  'drawYin' = 'drawYin',
  'acquireSpacingGuid' = 'acquireSpacingGuid',
  'constraint' = 'constraint',
  'getHei' = 'getHei',
  'height' = 'height',
  'unlock' = 'unlock',
  'or' = 'or',
  'saveTechBuy' = 'saveTechBuy',
  'byTechLess1' = 'byTechLess1',
  'byTech' = 'byTech',
  'getJian' = 'getJian',
  'getInf' = 'getInf',
  'getInf2' = 'getInf2',
}